export type OccasionKey =
  | "love"
  | "mothers-day"
  | "fathers-day"
  | "womens-day"
  | "birthday"
  | "appreciation"
  | "just-because"
  | "cheeky"
  | "apology"
  | "congratulations"
  | "closure"
  | "miss-you"
  | "thank-you"
  | "situationship"
  | "ex"
  | "confession"
  | "friend"
  | "faith";

export const OCCASIONS = {
  love: {
    key: "love",
    label: "Romantic Love",
    emoji: "❤️",
    title: "Create a Love Letter",
    subtitle: "Write something sweet, unforgettable, and deeply personal.",
    buttonText: "Create a love letter",
    path: "/create/love",
    senderRoles: [
      "Boyfriend",
      "Girlfriend",
      "Husband",
      "Wife",
      "Partner",
      "Fiancé / Fiancée",
      "Crush",
      "Secret Admirer",
      "Long-Distance Partner",
      "Someone in Love",
      "Other",
    ],
    recipientTypes: [
      "My Boyfriend",
      "My Girlfriend",
      "My Husband",
      "My Wife",
      "My Fiancé / Fiancée",
      "My Crush",
      "My Partner",
      "My Spouse",
      "Someone I'm Dating",
      "Long-Distance Love",
      "Someone Special",
      "Other",
    ],
    tones: ["Romantic", "Cute", "Poetic", "Playful", "Spicy PG-13"],
  },

  "mothers-day": {
    key: "mothers-day",
    label: "Mother’s Day",
    emoji: "🌸",
    title: "Create a Mother’s Day Letter",
    subtitle: "Write something beautiful for the woman who shaped your life.",
    buttonText: "Create a Mother’s Day letter",
    path: "/create/mothers-day",
    senderRoles: [
      "Son",
      "Daughter",
      "Child",
      "Grandchild",
      "Niece",
      "Nephew",
      "Brother",
      "Sister",
      "Husband / Partner",
      "Boyfriend",
      "Friend",
      "Family Friend",
      "Church Member",
      "Future father of your children",
      "Mentor",
      "Other",
    ],
    recipientTypes: [
      "My Mother",
      "My Wife",
      "Girlfriend",
      "Stepmother",
      "My Aunt",
      "My Sister",
      "My Mother-in-Law",
      "Mother of My Children",
      "Expecting Mother",
      "Single Mother",
      "Grandmother",
      "Church Mother",
      "Mother Figure",
      "Future Mother",
      "A Woman Who Will Make a Great Mother",
      "Other"
    ],
    tones: [
      "Heartfelt",
      "Grateful",
      "Emotional",
      "Inspirational",
      "Faith-based",
      "Lighthearted",
    ],
  },

  "fathers-day": {
    key: "fathers-day",
    label: "Father's Day",
    emoji: "🧔🏾‍♂️",
    title: "Create a Father's Day Letter",
    subtitle: "Write something grounded and grateful for the man who showed up.",
    buttonText: "Create a Father's Day letter",
    path: "/create/fathers-day",
    senderRoles: [
      "Son",
      "Daughter",
      "Child",
      "Stepchild",
      "Grandchild",
      "Niece",
      "Nephew",
      "Wife / Partner",
      "Co-parent",
      "Friend",
      "Family Member",
      "Church Member",
      "Mentee",
      "Other",
    ],
    recipientTypes: [
      "My Father",
      "My Husband",
      "My Partner",
      "Stepfather",
      "Grandfather",
      "Uncle",
      "Brother",
      "Father-in-Law",
      "Single Father",
      "Father Figure",
      "Expecting Father",
      "Mentor",
      "A Man Who Showed Up",
      "Other",
    ],
    tones: ["Warm", "Grounded", "Appreciative", "Respectful", "Lighthearted"],
  },

  "womens-day": {
  key: "womens-day",
  label: "Women’s Day",
  emoji: "🌷",
  title: "Create a Women’s Day Message",
  subtitle: "Celebrate the strength, beauty, and impact of women.",
  buttonText: "Create a Women’s Day message",
  path: "/create/womens-day",
  senderRoles: [
    "Friend",
    "Best Friend",
    "Partner",
    "Husband",
    "Boyfriend",
    "Sibling",
    "Child",
    "Parent",
    "Colleague",
    "Mentor",
    "Student",
    "Community Member",
    "Other",
  ],
  recipientTypes: [
    "Friend",
    "Best Friend",
    "Sister",
    "Daughter",
    "Wife",
    "Girlfriend",
    "Partner",
    "Mother",
    "Aunt",
    "Grandmother",
    "Mentor",
    "Colleague",
    "Boss",
    "Teacher",
    "Woman I admire",
    "Other",
  ],
  tones: [
    "Appreciative",
    "Empowering",
    "Inspirational",
    "Celebratory",
    "Heartfelt",
  ],
},

  birthday: {
    key: "birthday",
    label: "Birthday",
    emoji: "🎂",
    title: "Create a Birthday Letter",
    subtitle: "Make their day personal, warm, and unforgettable.",
    buttonText: "Create a birthday letter",
    path: "/create/birthday",
    senderRoles: [
      "Friend",
      "Best Friend",
      "Partner",
      "Boyfriend",
      "Girlfriend",
      "Husband",
      "Wife",
      "Crush",
      "Sibling",
      "Parent",
      "Child",
      "Cousin",
      "Aunt / Uncle",
      "Niece / Nephew",
      "Grandparent",
      "Grandchild",
      "Colleague",
      "Mentor",
      "Other",
    ],
    recipientTypes: [
      "Best Friend",
      "Friend",
      "Boyfriend",
      "Girlfriend",
      "Husband",
      "Wife",
      "Partner",
      "Crush",
      "Parent",
      "Mother",
      "Father",
      "Child",
      "Son",
      "Daughter",
      "Sibling",
      "Cousin",
      "Aunt / Uncle",
      "Niece / Nephew",
      "Grandparent",
      "Grandchild",
      "Colleague",
      "Mentor",
      "Other",
    ],
    tones: ["Warm", "Funny", "Heartfelt", "Celebratory"],
  },

  appreciation: {
    key: "appreciation",
    label: "Appreciation",
    emoji: "🙏",
    title: "Create an Appreciation Letter",
    subtitle: "Say thank you in a way they’ll actually remember.",
    buttonText: "Create an appreciation letter",
    path: "/create/appreciation",
    senderRoles: [
      "Friend",
      "Partner",
      "Family",
      "Child",
      "Sibling",
      "Colleague",
      "Employee",
      "Student",
      "Mentee",
      "Church Member",
      "Client",
      "Other",
    ],
    recipientTypes: [
      "Friend",
      "Partner",
      "Parent",
      "Family Member",
      "Sibling",
      "Mentor",
      "Teacher",
      "Boss",
      "Colleague",
      "Helper",
      "Pastor / Spiritual Leader",
      "Coach",
      "Client",
      "Other",
    ],
    tones: ["Warm", "Respectful", "Heartfelt", "Faith-based"],
  },

  "just-because": {
    key: "just-because",
    label: "Just Because",
    emoji: "💌",
    title: "Create a Just-Because Letter",
    subtitle: "No holiday needed. Just say what’s on your heart.",
    buttonText: "Create a just-because letter",
    path: "/create/just-because",
    senderRoles: [
      "Friend",
      "Best Friend",
      "Partner",
      "Boyfriend",
      "Girlfriend",
      "Spouse",
      "Crush",
      "Sibling",
      "Parent",
      "Child",
      "Family Member",
      "Secret Admirer",
      "Other",
    ],
    recipientTypes: [
      "Someone Special",
      "Friend",
      "Best Friend",
      "Partner",
      "Boyfriend",
      "Girlfriend",
      "Spouse",
      "Crush",
      "Parent",
      "Child",
      "Sibling",
      "Family Member",
      "Someone I Appreciate",
      "Other",
    ],
    tones: ["Sweet", "Heartfelt", "Poetic", "Playful"],
  },

  cheeky: {
    key: "cheeky",
    label: "Cheeky",
    emoji: "😏",
    title: "Create a Cheeky Letter",
    subtitle: "Write something playful, bold, flirty, and still tasteful.",
    buttonText: "Create a cheeky letter",
    path: "/create/cheeky",
    senderRoles: [
      "Crush",
      "Partner",
      "Situationship",
      "Almost Partner",
      "Friend",
      "Secret Admirer",
      "Someone Flirting",
      "Other",
    ],
    recipientTypes: [
      "Crush",
      "Partner",
      "Situationship",
      "Almost Partner",
      "Someone I'm Flirting With",
      "Someone I Like",
      "Someone Special",
      "Other",
    ],
    tones: ["Playful", "Bold", "Flirty", "Teasing", "Spicy PG-13"],
  },

  apology: {
    key: "apology",
    label: "Apology",
    emoji: "🙏",
    title: "Create an Apology Letter",
    subtitle: "Own what happened with sincerity, remorse, and emotional honesty.",
    buttonText: "Create an apology letter",
    path: "/create/apology",
    senderRoles: [
      "Partner",
      "Ex",
      "Friend",
      "Best Friend",
      "Sibling",
      "Parent",
      "Child",
      "Family Member",
      "Colleague",
      "Classmate",
      "Someone Who Hurt Them",
      "Other",
    ],
    recipientTypes: [
      "Partner",
      "Ex",
      "Friend",
      "Best Friend",
      "Sibling",
      "Parent",
      "Child",
      "Family Member",
      "Colleague",
      "Classmate",
      "Someone I Hurt",
      "Someone I Disappointed",
      "Other",
    ],
    tones: ["Sincere", "Accountable", "Gentle", "Remorseful", "Mature"],
  },

  congratulations: {
    key: "congratulations",
    label: "Congratulations",
    emoji: "🎉",
    title: "Create a Congratulations Letter",
    subtitle: "Celebrate their win by honoring the effort, journey, and growth behind it.",
    buttonText: "Create a congratulations letter",
    path: "/create/congratulations",
    senderRoles: [
      "Friend",
      "Best Friend",
      "Partner",
      "Parent",
      "Sibling",
      "Family Member",
      "Colleague",
      "Boss",
      "Mentor",
      "Teacher",
      "Coach",
      "Other",
    ],
    recipientTypes: [
      "Friend",
      "Best Friend",
      "Partner",
      "Child",
      "Sibling",
      "Family Member",
      "Colleague",
      "Employee",
      "Student",
      "Graduate",
      "New Parent",
      "Newly Engaged",
      "Newly Married",
      "Award Winner",
      "New Business Owner",
      "Achiever",
      "Other",
    ],
    tones: ["Celebratory", "Proud", "Uplifting", "Joyful", "Encouraging"],
  },

  closure: {
    key: "closure",
    label: "Closure",
    emoji: "🕊️",
    title: "Create a Closure Letter",
    subtitle: "Say goodbye with calm, gratitude, and a clean emotional ending.",
    buttonText: "Create a closure letter",
    path: "/create/closure",
    senderRoles: [
      "Ex",
      "Former Partner",
      "Former Friend",
      "Old Friend",
      "Partner",
      "Someone Letting Go",
      "Someone Apologizing",
      "Someone Choosing Peace",
      "Other",
    ],
    recipientTypes: [
      "Ex",
      "Former Partner",
      "Former Friend",
      "Old Friend",
      "Past Love",
      "Someone I Need Closure With",
      "Someone I Hurt",
      "Someone Who Hurt Me",
      "Other",
    ],
    tones: ["Calm", "Reflective", "Mature", "Grateful", "Bittersweet"],
  },

  "miss-you": {
    key: "miss-you",
    label: "Miss You",
    emoji: "🥺",
    title: "Create a Miss-You Letter",
    subtitle: "Keep it soft, simple, and honest about the ache of absence.",
    buttonText: "Create a miss-you letter",
    path: "/create/miss-you",
    senderRoles: [
      "Partner",
      "Long-Distance Partner",
      "Friend",
      "Best Friend",
      "Family",
      "Parent",
      "Child",
      "Sibling",
      "Ex",
      "Someone Far Away",
      "Other",
    ],
    recipientTypes: [
      "Partner",
      "Long-Distance Love",
      "Friend",
      "Best Friend",
      "Parent",
      "Child",
      "Sibling",
      "Family Member",
      "Ex",
      "Someone Far Away",
      "Someone I Miss",
      "Other",
    ],
    tones: ["Soft", "Emotional", "Simple", "Tender", "Longing"],
  },

  "thank-you": {
    key: "thank-you",
    label: "Thank You",
    emoji: "🤍",
    title: "Create a Thank-You Letter",
    subtitle: "Thank them for something specific in a warm, grounded way.",
    buttonText: "Create a thank-you letter",
    path: "/create/thank-you",
    senderRoles: [
      "Friend",
      "Partner",
      "Family",
      "Child",
      "Parent",
      "Sibling",
      "Student",
      "Mentee",
      "Employee",
      "Colleague",
      "Client",
      "Other",
    ],
    recipientTypes: [
      "Friend",
      "Partner",
      "Parent",
      "Family Member",
      "Sibling",
      "Mentor",
      "Teacher",
      "Coach",
      "Boss",
      "Colleague",
      "Helper",
      "Pastor / Spiritual Leader",
      "Client",
      "Other",
    ],
    tones: ["Warm", "Grateful", "Grounded", "Personal", "Thoughtful"],
  },

  situationship: {
    key: "situationship",
    label: "Situationship",
    emoji: "🤔",
    title: "Create a Situationship Letter",
    subtitle: "Be honest about the blurry, real, slightly messy feelings between you.",
    buttonText: "Create a situationship letter",
    path: "/create/situationship",
    senderRoles: [
      "Situationship",
      "Almost Partner",
      "Crush",
      "Friend With Feelings",
      "Talking Stage",
      "Someone Unsure",
      "Someone Catching Feelings",
      "Other",
    ],
    recipientTypes: [
      "Situationship",
      "Almost Partner",
      "Crush",
      "Friend With Feelings",
      "Talking Stage",
      "Someone I Like",
      "Someone Sending Mixed Signals",
      "Other",
    ],
    tones: ["Honest", "Modern", "Conflicted", "Direct", "Soft"],
  },

  ex: {
    key: "ex",
    label: "Ex",
    emoji: "🌙",
    title: "Create a Letter to an Ex",
    subtitle: "Express longing, acceptance, or unfinished feelings without desperation.",
    buttonText: "Create a letter to an ex",
    path: "/create/ex",
    senderRoles: [
      "Ex",
      "Former Partner",
      "Former Boyfriend",
      "Former Girlfriend",
      "Former Spouse",
      "Past Love",
      "Someone Still Healing",
      "Someone Moving On",
      "Other",
    ],
    recipientTypes: [
      "Ex",
      "Former Partner",
      "Former Boyfriend",
      "Former Girlfriend",
      "Former Spouse",
      "Past Love",
      "Someone I Used To Love",
      "Someone I Miss",
      "Someone I Need Peace With",
      "Other",
    ],
    tones: ["Controlled", "Emotional", "Honest", "Reflective", "Bittersweet"],
  },

  confession: {
    key: "confession",
    label: "Confession",
    emoji: "💭",
    title: "Create a Confession Letter",
    subtitle: "Reveal what you feel with vulnerability, tension, and courage.",
    buttonText: "Create a confession letter",
    path: "/create/confession",
    senderRoles: [
      "Friend",
      "Best Friend",
      "Crush",
      "Secret Admirer",
      "Colleague",
      "Classmate",
      "Someone Nervous",
      "Someone Taking a Risk",
      "Other",
    ],
    recipientTypes: [
      "Crush",
      "Friend",
      "Best Friend",
      "Someone I Like",
      "Someone Special",
      "Colleague",
      "Classmate",
      "Someone Who Doesn't Know Yet",
      "Other",
    ],
    tones: ["Vulnerable", "Direct", "Nervous", "Tender", "Bold"],
  },

  friend: {
    key: "friend",
    label: "Friend",
    emoji: "✨",
    title: "Create a Friendship Letter",
    subtitle: "Write something casual, warm, conversational, and full of personality.",
    buttonText: "Create a friendship letter",
    path: "/create/friend",
    senderRoles: [
      "Best Friend",
      "Close Friend",
      "Old Friend",
      "New Friend",
      "Childhood Friend",
      "Work Friend",
      "Long-Distance Friend",
      "Friend Who Became Family",
      "Other",
    ],
    recipientTypes: [
      "Best Friend",
      "Close Friend",
      "Old Friend",
      "New Friend",
      "Childhood Friend",
      "Work Friend",
      "Long-Distance Friend",
      "Friend Who Became Family",
      "Other",
    ],
    tones: ["Casual", "Warm", "Funny", "Real", "Affectionate"],
  },

  faith: {
    key: "faith",
    label: "Faith",
    emoji: "🕯️",
    title: "Create a Faith Letter",
    subtitle: "Share something spiritual, personal, and reflective without sounding preachy.",
    buttonText: "Create a faith letter",
    path: "/create/faith",
    senderRoles: [
      "Friend",
      "Partner",
      "Family",
      "Parent",
      "Child",
      "Sibling",
      "Church Member",
      "Pastor / Spiritual Leader",
      "Mentor",
      "Mentee",
      "Prayer Partner",
      "Other",
    ],
    recipientTypes: [
      "Friend",
      "Partner",
      "Parent",
      "Child",
      "Sibling",
      "Family Member",
      "Church Member",
      "Pastor / Spiritual Leader",
      "Mentor",
      "Mentee",
      "Prayer Partner",
      "Someone I Pray For",
      "Someone Needing Encouragement",
      "Other",
    ],
    tones: ["Reflective", "Respectful", "Spiritual", "Prayerful", "Gentle"],
  },
} as const;

export function getOccasion(key: string) {
  return OCCASIONS[key as OccasionKey] ?? null;
}
